//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int PenaltyId { get; set; }
        public int BorrowId { get; set; }
        public decimal Penalty1 { get; set; }
    
        public virtual Borrow Borrow { get; set; }
    }
}
